In [2]:
import numpy as np

In [3]:
x = np.eye(3) * 9
x

array([[9., 0., 0.],
       [0., 9., 0.],
       [0., 0., 9.]])

In [11]:
x = np.arange(2, 33, 2).reshape(4, 4)

mean = x.mean()
std = x.std()
y = np.abs(x - mean) <= (std * 0.5)

print(x, "\n", x[y])

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]] 
 [14 16 18 20]


In [12]:
arr = np.zeros((9, 9), dtype=int)
arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [13]:
n = int(input())

arr = np.arange(1, 1 + n).reshape(1, n)
arr = np.ones((n, 1)) * arr

print(arr)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
